steps:
  - name: "gcr.io/cloud-builders/java/mvn"
    env: ["PROJECT_ROOT=wxdailysummary"]
    args: ["install"]
    id: "mvn-install"

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/wxdailysummary:${TAG_NAME}", "."]
    dir: 'wxdailysummary-microservice/src/main/docker'
    id: "docker-wxdailysummary-build"

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/movies-ui:${TAG_NAME}", "."]
    dir: 'movies-ui/src/main/docker'
    id: "docker-moviesui-build"

images: ["gcr.io/${PROJECT_ID}/wxdailysummary:${TAG_NAME}", "gcr.io/${PROJECT_ID}/movies-ui:${TAG_NAME}"]