steps:
  - name: "gcr.io/cloud-builders/java/mvn"
    env: ["PROJECT_ROOT=wxdailysummary"]
    args: ["install"]
    id: "mvn-install"

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/wxdailysummary:0.0.1-dev", "-f", "spring-cloud-microservice-example/wxdailysummary-microservice/src/main/docker/Dockerfile"]
    id: "docker-wxdailysummary-build"

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/movies-ui:0.0.1-dev", "-f", "spring-cloud-microservice-example/movies-ui/src/main/docker/Dockerfile"]
    id: "docker-moviesui-build"

images: ["gcr.io/${PROJECT_ID}/wxdailysummary:0.0.1-dev"]