apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: wxdailysummary-controller
  name: wxdailysummary
spec:
  ports:
  - name: "8765"
    port: 8765
    targetPort: 8765
  selector:
    io.kompose.service: wxdailysummary-controller
status:
  loadBalancer: {}
