server:
  port: 8765

ribbon:
  eureka:
    enabled: true

#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test
#    username: root

spring:
 jpa:
   database-platform: org.hibernate.dialect.H2Dialect
   show-sql: false
   ddl-auto: create
   hibernate:
    naming:
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

